Repository EGI-Federation/documentation, pull requests merged in 2020-10, with the labels that each got.

#73 Improve contributing guide
  .prettierrc.toml
  .travis.yml
  CONTRIBUTING.md
  README.md
  content/en/_index.md
  content/en/about/_index.md
  content/en/about/concepts/_index.md
  content/en/about/contributing/_index.md
  content/en/about/style/_index.md
Labels: documentation, enhancement

#78 about: split git usage to a dedicated page
  content/en/about/contributing/_index.md
  content/en/about/git/_index.md
  content/en/about/style/_index.md
Labels: hacktoberfest-accepted

#81 Document running and testing site.
  content/en/about/git/_index.md
Labels: hacktoberfest-accepted

#80 Small fixes, unmix git and gh
  content/en/about/git/_index.md
Labels: hacktoberfest-accepted

#79 Online Storage documentation
  content/en/users/cloud-compute/storage/_index.md
  content/en/users/online-storage/_index.md
  content/en/users/online-storage/grid-storage/_index.md
  content/en/users/online-storage/object-storage/_index.md
Labels: hacktoberfest-accepted

#82 Update _index.md
  content/en/users/cloud-compute/gpgpu/_index.md
Labels: documentation

#84 Andrea's review
  content/en/users/notebooks/_index.md
  content/en/users/notebooks/data/_index.md
  content/en/users/notebooks/faq/_index.md
  content/en/users/notebooks/kernels/_index.md
  content/en/users/notebooks/training/_index.md
  content/en/users/notebooks/training/new-classic.png
Labels: hacktoberfest-accepted

#77 Workload manager
  content/en/users/workload-manager/_index.md
  content/en/users/workload-manager/dirac_web_portal.png
  content/en/users/workload-manager/egi_workload_manager_web_portal.png
  content/en/users/workload-manager/job_monitor.png
  content/en/users/workload-manager/job_submit.png
  content/en/users/workload-manager/proxy_cert_upload_1.png
  content/en/users/workload-manager/proxy_cert_upload_2.png
Labels: hacktoberfest-accepted

#76 Gianni review 2
  README.md
  content/en/users/cloud-compute/_index.md
  content/en/users/cloud-compute/auth/_index.md
  content/en/users/cloud-compute/vmi/_index.md
Labels: hacktoberfest-accepted

#83 HTC documentation review
  CODEOWNERS
  content/en/users/high-throughput-compute/_index.md
  content/en/users/high-throughput-compute/htc_archtecture.png
  content/en/users/htc/.DS_Store
  content/en/users/htc/_index.md
  content/en/users/htc/getting-started/.DS_Store
Labels: hacktoberfest-accepted

#113 updated gitignore
  .gitignore
  content/en/providers/datahub/.DS_Store
  content/en/providers/datahub/oneprovider/.DS_Store
  content/en/users/data-transfer/.DS_Store
  content/en/users/data-transfer/monitoring/.DS_Store
Labels: hacktoberfest-accepted
