Repository EGI-Federation/documentation, pull requests merged in 2022-07, with the labels that each got.

#465 [Check-in] Migrate Production endpoints to Keycloak based OP
  content/en/providers/check-in/sp/_index.md
  content/en/providers/cloud-compute/openstack/aai.md
  content/en/providers/cloud-compute/openstack/vo_config.md
  content/en/providers/notebooks/architecture/_index.md
  content/en/users/compute/cloud-compute/openstack/_index.md
  content/en/users/data/management/datahub/api/_index.md
  content/en/users/getting-started/cli/_index.md
Labels: safe for preview

#453 New tutorial on Jupyter and DataHub
  content/en/users/tutorials/jupyter-datahub-virtual-machine/_index.md
  content/en/users/tutorials/jupyter-datahub-virtual-machine/edit-mount.sh.png
  content/en/users/tutorials/jupyter-datahub-virtual-machine/run-mount.sh.png
Labels: safe for preview

#467 Update documentation for Oneprovider installation
  content/en/providers/check-in/sp/_index.md
  content/en/providers/datahub/oneprovider/_index.md
  content/en/providers/datahub/oneprovider/onedatify-oneprovider-expose.png
  content/en/providers/datahub/oneprovider/onedatify-oneprovider.png
Labels: safe for preview

#469 Openstack keycloak review
  content/en/providers/cloud-compute/openstack/aai.md
Labels: safe for preview

#475 Document certificate provisioning
  content/en/internal/collaboration-tools/_index.md
  content/en/internal/collaboration-tools/certificates/_index.md
Labels: safe for preview

#476 [Check-in] Add instructions for obtaining tokens using oidc-agent
  content/en/providers/check-in/sp/_index.md
  content/en/users/aai/check-in/obtaining-tokens/oidc-agent/_index.md
Labels: check-in

#473 COU admin role vs membership
  content/en/users/aai/check-in/vos/_index.md
Labels: safe for preview, check-in

#477 [Check-in] Add OP migration section in the end-user guide
  content/en/providers/check-in/sp/_index.md
  content/en/users/aai/check-in/obtaining-tokens/oidc-agent/_index.md
  content/en/users/aai/check-in/obtaining-tokens/token-portal/_index.md
Labels: safe for preview, check-in

#479 Add a warning about the config of Require claim
  content/en/providers/cloud-compute/openstack/aai.md
Labels: safe for preview

#480 Add screenshots to select Check-In in Horizon
  content/en/users/compute/cloud-compute/openstack/_index.md
  content/en/users/getting-started/openstack/_index.md
  content/en/users/getting-started/openstack/dashboard-login-check-in-1.png
  content/en/users/getting-started/openstack/dashboard-login-check-in-2.png
  content/en/users/getting-started/openstack/dashboard-login-check-in-3.png
  content/en/users/getting-started/openstack/dashboard-login-check-partb.png
Labels: safe for preview
