Repository EGI-Federation/documentation, pull requests merged in 2022-10, with the labels that each got.

#509 creation of the ROD pages
  content/en/providers/rod/_index.md
  content/en/providers/rod/alarms-tickets/_index.md
  content/en/providers/rod/communication/_index.md
  content/en/providers/rod/downtimes/_index.md
  content/en/providers/rod/duties/_index.md
  content/en/providers/rod/faq/_index.md
  content/en/providers/rod/overview/_index.md
  content/en/providers/rod/security/_index.md
Labels: safe for preview

#512 Remove links to EGI Marketplace
  content/en/users/compute/cloud-compute/auth/_index.md
  content/en/users/compute/cloud-compute/faq/_index.md
  content/en/users/compute/orchestration/workload-manager/_index.md
  content/en/users/getting-started/_index.md
Labels: safe for preview

#515 Document oidc-agent, fedcloudclient and terraform
  .gitignore
  CODEOWNERS
  content/en/users/tutorials/oidc-agent-fedcloudclient-terraform/_index.md
Labels: safe for preview

#527 GitHub actions: use updated octokit call
  .github/workflows/deploy_pr_preview.yml
Labels: bug

#518 [Check-in] Remove references to MITREid Connect from SP guide
  content/en/providers/check-in/sp/_index.md
Labels: safe for preview, check-in

#534 Fix wrong up to GET_OUTPUT introduced in #526
  .github/workflows/deploy_pr_preview.yml
Labels: bug

#533 New API documentation for AppDB
  content/en/users/compute/cloud-compute/appdb/_index.md
Labels: safe for preview
