Repository EGI-Federation/documentation, pull requests merged in 2023-01, with the labels that each got.

#563 Add site-specific docs
  content/en/users/compute/cloud-container-compute/docker/_index.md
  content/en/users/service-providers/_index.md
Labels: safe for preview

#398 Added Perun documentation section
  content/en/users/aai/check-in/vos/perun/_index.md
Labels: safe for preview, check-in

#565 Adding usecases and requirements to Rucio
  content/en/users/data/management/rucio/_index.md
Labels: safe for preview

#564 Storage import
  content/en/providers/datahub/oneprovider/_index.md
  content/en/providers/datahub/oneprovider/storage-import-01.png
Labels: safe for preview

#560 checkin_rest_api_documentation_improvements
  content/en/users/aai/check-in/vos/_index.md
Labels: safe for preview, check-in

#559 Get entitlements with new token portal
  content/en/users/aai/check-in/obtaining-tokens/token-portal/_index.md
Labels: check-in

#566 [Check-in] Add example configurations for Keycloak Services
  content/en/providers/check-in/idp/_index.md
  content/en/providers/check-in/sp/_index.md
  content/en/providers/check-in/sp/oidc-examples-keycloak-add-oidc-idp-1.png
  content/en/providers/check-in/sp/oidc-examples-keycloak-add-oidc-idp-2.png
  content/en/providers/check-in/sp/oidc-examples-keycloak-idp.png
  content/en/providers/check-in/sp/oidc-examples-keycloak-oidc-eduperson-entitlement-mapper.png
  content/en/providers/check-in/sp/oidc-examples-keycloak-oidc-idp-advanced.png
  content/en/providers/check-in/sp/oidc-examples-keycloak-oidc-idp-oidc.png
  content/en/providers/check-in/sp/oidc-examples-keycloak-oidc-voperson-id-mapper.png
  content/en/providers/check-in/sp/saml-examples-keycloak-add-saml-idp-1.png
  content/en/providers/check-in/sp/saml-examples-keycloak-add-saml-idp-2.png
  content/en/providers/check-in/sp/saml-examples-keycloak-idp.png
  content/en/providers/check-in/sp/saml-examples-keycloak-saml-edupersonentitlement-mapper.png
  content/en/providers/check-in/sp/saml-examples-keycloak-saml-idp-advanced.png
  content/en/providers/check-in/sp/saml-examples-keycloak-saml-idp-saml-setting.png
  content/en/providers/check-in/sp/saml-examples-keycloak-saml-vopersonid-mapper.png
  content/en/users/aai/check-in/_index.md
  content/en/users/aai/check-in/faq/_index.md
  content/en/users/compute/cloud-compute/_index.md
  content/en/users/getting-started/_index.md
Labels: safe for preview

#570 Theme improvements
  assets/icons/logo.svg
  assets/scss/_variables_project.scss
  config.toml
  content/en/_index.md
  content/en/users/compute/high-throughput-compute/querying-information-system/_index.md
  static/css/egi.css
Labels: safe for preview

#567 Secrets Store documentation
  .gitignore
  content/en/about/contributing/shortcodes/_index.md
  content/en/users/data/management/data-transfer/_index.md
  content/en/users/data/management/data-transfer/api/_index.md
  content/en/users/data/management/datahub/api/_index.md
  content/en/users/data/management/datahub/clients/_index.md
  content/en/users/machine-learning/_index.md
  content/en/users/security/_index.md
  content/en/users/security/secrets-store/_index.md
  content/en/users/security/secrets-store/api/_index.md
  content/en/users/security/secrets-store/architecture/_index.md
  content/en/users/security/secrets-store/architecture/sstore-design.png
  content/en/users/security/secrets-store/cli/_index.md
  content/en/users/security/secrets-store/gui/_index.md
  content/en/users/security/secrets-store/gui/vault-create-secret.png
  content/en/users/security/secrets-store/gui/vault-home-directory.png
  content/en/users/security/secrets-store/gui/vault-homes.png
  content/en/users/security/secrets-store/gui/vault-login-oidc.png
  content/en/users/security/secrets-store/gui/vault-main-window.png
Labels: safe for preview
